# NOTE: This file is not used for packaging.
#       We still stick up with setupools & setup.py

[tool.black]
line-length = 120
target-version = ['py37']  # Stay on 3.7 since is the minimal we support
include = '\.py$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | setup.py       # https://github.com/psf/black/issues/1288#issuecomment-653781179
  )/
)
'''

[tool.isort]
ensure_newline_before_comments = true
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses= true
line_length = 120
